import NextTopLoader from "nextjs-toploader";
import { Inter } from "next/font/google";
import "./globals.css";
import LoadingScreen from "@/components/loadingScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Rinjani Visitor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader showSpinner={false} />
        {children}
        <LoadingScreen />
      </body>
    </html>
  );
}
